'use client'
import { Inter, Lexend, Prosto_One } from 'next/font/google'
import './globals.css'
import Provider from './themeProvider';
import '@rainbow-me/rainbowkit/styles.css'


import { getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit'
import { configureChains, createConfig, WagmiConfig } from 'wagmi'
import { arbitrumSepolia } from 'wagmi/chains'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { publicProvider } from 'wagmi/providers/public'
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc'

const inter = Inter({ subsets: ['latin'] });

const lexend = Lexend({ subsets: ['latin'] });

const prosto_one = Prosto_One({ subsets: ['latin'], weight: ['400'] });

// export const metadata = {
//   title: 'FreedFi',
//   description: 'Generated by create next app',
// };

const projectId = process.env.NEXT_PUBLIC_PROJECTID
const http = process.env.NEXT_PUBLIC_ALCHEMY_KEY

const { chains, publicClient } = configureChains(
  [arbitrumSepolia],
  [
    jsonRpcProvider({
      rpc: (chain) => ({
        http
      }),
    }),
  ],
)

const { connectors } = getDefaultWallets({
  appName: 'FreedFi',
  projectId,
  chains,
})

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
})

export default function RootLayout({ children}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider chains={chains}>
            <Provider>{children}</Provider>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  )
}




// import { Inter, Lexend, Prosto_One } from 'next/font/google';
// import './globals.css';
// import Provider from './themeProvider';

// const inter = Inter({ subsets: ['latin'] });

// const lexend = Lexend({ subsets: ['latin'] });

// const prosto_one = Prosto_One({ subsets: ['latin'], weight: ['400'] });

// export const metadata = {
//   title: 'FreedFi',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${prosto_one.className} dark:bg-black  bg-white text-gray-800 dark:text-gray-100`}>
//         <Provider>{children}</Provider>
//       </body>
//     </html>
//   );
// }
