import { Inter, Lexend, Prosto_One } from 'next/font/google';
import './globals.css';
import Provider from './themeProvider';

const inter = Inter({ subsets: ['latin'] });

const lexend = Lexend({ subsets: ['latin'] });

const prosto_one = Prosto_One({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${prosto_one.className} dark:bg-black  bg-white text-gray-800 dark:text-gray-100`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
